### ISSUE TITLE
`Yield` returns `None`

### ISSUE THREAD

**Issue by roaldarbol** [BrianPugh/belay#62] opened 2022-12-02 10:41 UTC
I think there may have been a breaking change somewhere. I'm trying a simple generator function, but I only get `None` yields. Tried on both my Mac and a student's Windows with Belay `0.15`.
```python

from belay import Device
import time

class PicoW(Device):
    @Device.task
    def my_generator():
        i = 0
        while i < 10:
            yield i
            i += 1

if __name__ == "__main__":
    picoW = PicoW(list_devices()[-1])
    values = []
    for val in picoW.my_generator():
        values.append(val)
    picoW.close()
    print(values)
# [None, None, None, None, None, None, None, None, None, None]
```
If I print from within the generator I get the correct values, so I believe they're lost during transit somewhere.
I also tried in the old-fashioned way without a class, getting the same results.

**Comment by roaldarbol** [comment] 2022-12-02 11:11
Maybe we'll need to add a test asserting generator output?

**Comment by BrianPugh** [comment] 2022-12-02 16:34
I accidentally broke this in f7244cbe6d7816ee54f8ba96bf92c20f4acc816f. What happened is that the belay-internal function used for getting the next element of a generator was being interpreted as a generic expression, which lead to some downstream issues. This is fixed in 33fe6dc18159288d0ee2303cb0f91f8a2885b3c0 and release `v0.15.1`.

The fix is a little bit of a hack, but it's a very minimal change. The proper code should be a little bit simpler since that commit fixed expressions. Since broken code is becoming an issue, I definitely want to setup more integration tests before adding new features/more refactoring. I've been avoiding it a bit at this point because its not exactly easy to setup for this. I'm unavailable for a few days, but will work on it when I get back.

**Closed** 2022-12-02 16:51 UTC

**Comment by roaldarbol** [comment] 2022-12-02 18:21
Thanks! Checked and works for me👌

**Comment by BrianPugh** [comment] 2022-12-06 23:40
Setup and added integration tests in #63 , so that this shouldn't happen in the future (and if breaks do happen, we can now easily add integration tests to prevent regressions).
